# Generated by Django 4.1.4 on 2022-12-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='trabaja',
        ),
        migrations.AlterField(
            model_name='familiar',
            name='fecha_de_nacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
