# Generated by Django 4.1.4 on 2022-12-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fam', '0002_remove_familiar_trabaja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='fecha_de_nacimiento',
        ),
    ]
